### PR TITLE
Added a minimal extent for the seach to zoom at.

### PR DESCRIPTION
**Pull request by fabanc**
When zooming on a point the search widget, the widget has a tendency to
go beyond the maximum zoom level supported by ArcGIS Online base maps.
This proposed fix sets a minimum scale for the search widget, to keep it
visible with the basemap, when the result set does not have an extent.

### CODE REVIEW

**Review by Horiatu — COMMENTED** [review]
Please do not fix spaces and alignment on pull requests (or make a separate pull request for those.)
Now it is impossible to spot the changes since most of the file is highlighted with changes...

**Review by Horiatu — COMMENTED** [review]
I cannot spot the difference. Please guide me to the line number where the changes start.

**Comment by fabanc** [comment]
Yes. I don't know why Atom does that by default. I am suspecting different setting for writing end of line characters. Change is at line 1542. Search for:  search.zoomScale = 25000;

**Comment by Horiatu** [comment]
Done it, but don’t see any changes in my set. Please test it fully…

Done another check-in – please observe some changes around that line.

Tx,

Horia Tudosie | Lead Developer
Esri Canada | 900-12 Concorde Pl | Toronto ON M3C 3R8
T 647-943-1841 | esri.ca<http://esri.ca/>

**Pull request merged**
